[package]
name = "actiontui"
version = "0.1.0"
description = "A TUI to run and monitor Github Actions"
authors = ["nick"]
license = "MIT"
edition = "2024"

[dependencies]
clap = "4.6.1"
color-eyre = "0.6.3"
confy = "2.0.0"
crossterm = "0.29.0"
ratatui = "0.30.1"
reqwest = { version = "0.13.3", features = ["json", "blocking"] }
serde = {version = "1.0.228", features = ["derive"] }
serde_derive = "1.0.228"
serde_json = "1.0.149"
chrono = { version = "0.4.39", features = ["serde"] }
tui-widget-list = "0.15.2"
tempfile = "3.27.0"

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
